import { TranslationStrings } from './types';

export const TRANSLATIONS: TranslationStrings = {
  app_name: { fr: 'AuraScribe', en: 'AuraScribe' },

  // Greetings and common phrases
  hello: { fr: 'Bonjour', en: 'Hello' },
  welcome: { fr: 'Bienvenue', en: 'Welcome' },

  // Notifications and alerts
  law25_purge: { fr: 'Purge Loi 25', en: 'Law 25 Purge' },
  sessions_deleted_compliance: { fr: 'sessions ont été supprimées définitivement pour conformité.', en: 'sessions were permanently deleted for compliance.' },
  login_successful: { fr: 'Connexion réussie', en: 'Login Successful' },
  aura_swarm_complete: { fr: 'Swarm Aura terminé', en: 'Aura Swarm Complete' },
  documentation_ready: { fr: 'Documentation prête.', en: 'Documentation is ready.' },
  documentation_for: { fr: 'Documentation pour', en: 'Documentation for' },
  mado_alert_detected: { fr: 'ALERTE MADO DÉTECTÉE', en: 'MADO ALERT DETECTED' },
  mado_requires_signature: { fr: 'Une maladie à déclaration obligatoire nécessite votre signature.', en: 'A mandatory reportable disease requires your signature.' },
  new_ai_tasks: { fr: 'Nouvelles tâches IA', en: 'New AI Tasks' },
  actions_extracted: { fr: 'actions extraites de la session.', en: 'actions extracted from the session.' },
  ramq_billing: { fr: 'Facturation RAMQ', en: 'RAMQ Billing' },
  transmission_completed: { fr: 'Transmission vers le portail effectuée.', en: 'Transmission to the portal completed.' },

  // Confirmations
  confirm_delete_session: { fr: 'Êtes-vous sûr de vouloir supprimer cette session ?', en: 'Are you sure you want to delete this session?' },

  // Status messages
  expired: { fr: 'Expiré', en: 'Expired' },
  no_sessions: { fr: 'Aucune session enregistrée.', en: 'No sessions recorded.' },
  module_pending: { fr: 'Module en attente', en: 'Module pending' },
  module_in_development: { fr: 'est en cours de développement.', en: 'is under development.' },
  new_session: { fr: 'Nouvelle session', en: 'New Session' },
  view_sessions: { fr: 'Mes sessions', en: 'View Sessions' },
  ask_aura: { fr: 'Demander à Aura', en: 'Ask Aura' },
  auralink: { fr: 'AuraLink', en: 'AuraLink' },
  ramq: { fr: 'Facturation RAMQ', en: 'RAMQ Billing' },
  tasks: { fr: 'Tâches & rappels', en: 'Tasks & Reminders' },
  schedule: { fr: 'Calendrier', en: 'Schedule' },
  templates: { fr: 'Modèles & protocoles', en: 'Templates & Protocols' },
  community: { fr: 'Communauté clinique', en: 'Clinical Community' },
  settings: { fr: 'Paramètres', en: 'Settings' },
  request_feature: { fr: 'Suggérer une fonction', en: 'Request Feature' },
  logout: { fr: 'Déconnexion', en: 'Logout' },
  consent_taken: { fr: 'Consentement du patient obtenu', en: 'Patient consent taken' },
  consent_not_required: { fr: 'Non requis (Décret)', en: 'Not required (Decree)' },
  law25_info: {
    fr: 'Information obligatoire (Loi 25) : le patient doit être informé que la session est enregistrée à des fins cliniques par une IA.',
    en: 'Mandatory information (Law 25): the patient must be informed that this session is recorded for clinical documentation by an AI.'
  },
  patient_info: { fr: 'Informations du patient', en: 'Patient Information' },
  full_name: { fr: 'Nom complet', en: 'Full Name' },
  dob: { fr: 'Date de naissance', en: 'Date of Birth' },
  ramq_number: { fr: 'Numéro RAMQ', en: 'RAMQ Number' },
  postal_code: { fr: 'Code postal', en: 'Postal Code' },
  scan_ramq: { fr: 'Scanner la carte RAMQ', en: 'Scan RAMQ Card' },
  start_recording: { fr: 'Démarrer l’enregistrement', en: 'Start Recording' },
  pause_recording: { fr: 'Pause', en: 'Pause' },
  resume_recording: { fr: 'Reprendre', en: 'Resume' },
  stop_recording: { fr: 'Terminer et générer', en: 'Stop and Generate' },
  physician_review_req: {
    fr: "Attention : ces documents sont générés par IA. Une révision médicale est requise pour validation.",
    en: 'Attention: these documents were AI-generated. Physician review and validation are mandatory.'
  },
  deletion_warning: {
    fr: 'Note : tous les formulaires sont éliminés automatiquement au bout de 24 heures (Loi 25 / PIPEDA).',
    en: 'Important note: all forms are automatically deleted within 24 hours of creation (Law 25 / PIPEDA).'
  },
  delete_session: { fr: 'Supprimer la session', en: 'Delete session' },
  status_validated: { fr: 'Validé', en: 'Validated' },
  status_pending: { fr: 'En attente', en: 'Pending' },
  read_more: { fr: 'Lire la suite', en: 'Read More' },
  latest_studies: { fr: 'Dernières études & évidences', en: 'Latest Studies & Evidence' },
  study_case_summary: { fr: 'Sommaire du cas clinique', en: 'Clinical Case Summary' },
  evidence_blog: { fr: 'Blogue d’évidences médicales', en: 'Medical Evidence Blog' },
  specialist_insights: { fr: 'Avis de spécialistes', en: 'Specialist Insights' },
  auralink_secure: { fr: 'Pipeline sécurisé AuraLink', en: 'AuraLink Secure Pipeline' },
  share_clinical_file: { fr: 'Partager un fichier clinique', en: 'Share a Clinical File' },
  recipient_email: { fr: 'Courriel du destinataire', en: 'Recipient Email' },
  permissions: { fr: 'Permissions', en: 'Permissions' },
  permission_read: { fr: 'Lecture seule', en: 'Read Only' },
  permission_download: { fr: 'Téléchargement autorisé', en: 'Allow Download' },
  permission_edit: { fr: 'Modification autorisée', en: 'Allow Edit' },
  anti_capture: { fr: 'Protection anti-capture (Loi 25)', en: 'Anti-Capture Protection (Law 25)' },
  expiration_time: { fr: "Délai d'expiration", en: 'Expiration Time' },
  security_method: { fr: 'Méthode de sécurité', en: 'Security Method' },
  generate_token: { fr: 'Générer un jeton unique', en: 'Generate Secure Token' },
  set_password: { fr: 'Définir un mot de passe', en: 'Set a Password' },
  active_transfers: { fr: 'Transferts actifs', en: 'Active Transfers' },
  soap_note: { fr: 'Note SOAP', en: 'SOAP Note' },
  prescription: { fr: 'Prescription', en: 'Prescription' },
  lab_order: { fr: 'Requête labo', en: 'Lab Order' },
  patient_note: { fr: 'Note patient', en: 'Patient Note' },
  referral: { fr: 'Lettre de référence', en: 'Referral Letter' },
  mado: { fr: 'MADO AS-770', en: 'MADO AS-770' },
  work_accident: { fr: 'Accident de travail (CNESST)', en: 'Work Accident (CNESST)' },
  doctor_note: { fr: 'Certificat médical', en: "Doctor's Note" },
  priority_high: { fr: 'Priorité haute', en: 'High Priority' },
  priority_medium: { fr: 'Priorité moyenne', en: 'Medium Priority' },
  priority_low: { fr: 'Priorité basse', en: 'Low Priority' },
  add_task: { fr: 'Ajouter une tâche', en: 'Add Task' },
  ai_generated_task: { fr: 'Généré par l’agent Aura', en: 'Generated by Aura Agent' },
  add_template: { fr: 'Nouveau modèle', en: 'New Template' },
  is_public: { fr: 'Publier dans la communauté', en: 'Publish to Community' },
  is_private: { fr: 'Modèle privé', en: 'Private Template' },
  template_author: { fr: 'Auteur', en: 'Author' },
  province: { fr: 'Province', en: 'Province' },
  category: { fr: 'Catégorie', en: 'Category' },
  generate_with_ai: { fr: 'Générer avec Aura IA', en: 'Generate with Aura AI' },
  bill_patient: { fr: 'Facturer RAMQ', en: 'Bill RAMQ' },
  bill_sent: { fr: 'Facture envoyée', en: 'Bill Sent' },
  billing_codes: { fr: 'Codes de facturation', en: 'Billing Codes' },
  suggest_codes: { fr: 'Suggérer des codes (IA)', en: 'Suggest Codes (AI)' },
  previous_bills: { fr: 'Historique de facturation', en: 'Billing History' },
  billing_engine: { fr: 'Moteur de facturation RAMQ', en: 'RAMQ Billing Engine' },
  amount: { fr: 'Montant', en: 'Amount' },
  diagnostic_code: { fr: 'Code diagnostique', en: 'Diagnostic Code' },
  service_code: { fr: 'Code de service', en: 'Service Code' },
  settings_profile: { fr: 'Profil & identité', en: 'Profile & Identity' },
  settings_storage: { fr: 'Stockage & Loi 25', en: 'Storage & Law 25' },
  settings_lab: { fr: 'Aura Lab (IA)', en: 'Aura Lab (AI)' },
  settings_integrations: { fr: 'Intégrations EMR & fax', en: 'EMR & Fax Integrations' }
};
